export const items: { type?: string; image: string; title: string; description: string }[] = [
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "img",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
    {
        type: "video",
        image: "/images/feedbacks/1.png",
        title: "Иванов Иван Иванович",
        description: "Продавец",
    },
];
