export const districts: { value: string; coordinates: { lat: number; lng: number } }[] = [
    { value: "Адмиралтейский", coordinates: { lat: 59.57, lng: 30.19 } },
    { value: "Василеостровский", coordinates: { lat: 54.6, lng: 30.6 } },
    { value: "Гражданский", coordinates: { lat: 54.6, lng: 30.6 } },
    { value: "Кировский", coordinates: { lat: 54.6, lng: 30.6 } },
    { value: "Колпинский", coordinates: { lat: 54.6, lng: 30.6 } },
    { value: "Красногвардейский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Красносельский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Кронштадтский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Московский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Невский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Петроградский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Петродворцовый", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Приморский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Пушкинский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Фрунзенский", coordinates: { lat: 54.6, lng: 20.6 } },
    { value: "Центральный", coordinates: { lat: 54.6, lng: 20.6 } },
];
